apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qtech-dosage-control-ui
  name: qtech-dosage-control-ui
  namespace: $KUBE_NAME_SPACE
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: qtech-dosage-control-ui
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qtech-dosage-control-ui
    spec:
      imagePullSecrets:
        - name: $DOCKER_CREDENTIAL_ID  # 提前在项目下配置访问阿里云的账号密码
      containers:
        - image: $REGISTRY/$DOCKERHUB_NAMESPACE/qtech-dosage-control-ui:latest
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: IfNotPresent
          name: app
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: nginx-config
              mountPath: "/etc/nginx/conf.d/"
              readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: qtech-dosage-control-ui
  name: qtech-dosage-control-ui
  namespace: $KUBE_NAME_SPACE
spec:
  ports:
    - name: http
      nodePort: 30013
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: qtech-dosage-control-ui
  sessionAffinity: None
  type: NodePort
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: $KUBE_NAME_SPACE
data:
  default.conf: |
    server {
          listen       80;
          server_name  nginx-server;
          location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
            index  index.html index.htm;
          }

          location /prod-api/ {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://qtech-admin.qtech-dosage-control-system:8080/;
          }

          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
            root   html;
          }
        }

